name: "Build and Test"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      token:
        required: true
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7

      - name: "Set Up JDK"
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: "Grant execute permission for gradlew"
        if: ${{ matrix.os != 'windows-latest' }}
        run: chmod +x gradlew

      - name: "Build with Gradle"
        run: ./gradlew build -x check
        shell: bash

      - name: "Tests"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: ./gradlew cleanJvmTest jvmTest --tests "com.ucasoft.kcron.*"

      - name: "Tests"
        if: ${{ matrix.os == 'windows-latest' }}
        run: ./gradlew cleanMingwX64Test mingwX64Test --tests "com.ucasoft.kcron.*"

      - name: "Tests"
        if: ${{ matrix.os == 'macos-latest' }}
        run: ./gradlew cleanMacosArm64Test macosArm64Test --tests "com.ucasoft.kcron.*"

      - name: "Tests Report"
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        if: success() || failure()
        with:
          name: jUnit Tests
          path: '**/build/test-results/*Test/TEST-*.xml'
          reporter: java-junit

      - name: "Run Coverage"
        if: ${{ github.event_name == 'pull_request' }}
        run: ./gradlew koverXmlReport
        shell: bash

      - name: "Coverage Report"
        uses: mi-kas/kover-report@94d69bc9d417de89b808cd5fe846bca2840911bb
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: |
            ./kcron-common/build/reports/kover/report.xml
            ./kcron-core/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Coverage Report"
          update-comment: true
